version: '3.3'
services:
  bootnode:
    # note: bootnode requires alltools
    image: "192.168.15.1:5000/armbuilds/client-all"
    deploy:
      placement:
        constraints:
          - node.hostname == 402raspberrypi_1
      replicas: 1
    configs:
      - source: genesis_block
        target: /root/genesis.json
      - source: bootnode_key
        target: /root/bootnode.key
    networks:
      - ethnet
    entrypoint:
      - sh
      - -c
    command: >-
      "geth --datadir /root/data init /root/genesis.json
      && bootnode --nodekey /root/bootnode.key"

  customer:
    # On x86: "ethereum/client-go:stable"
    image: "192.168.15.1:5000/armbuilds/client"
    deploy:
      replicas: 5
    depends_on:
      - bootnode
    configs:
      - source: genesis_block
        target: /root/genesis.json
      - source: bootnode_url
        target: /root/bootnode
    networks:
      - ethnet
    entrypoint:
      - sh
      - -c
    # Startup is delayed to give the bootnode time to start
    # The enode url must be constructed at runtime because it needs an IP address
    command: >-
      "geth --datadir /root/data init /root/genesis.json
      && sleep 10
      && geth --datadir /root/data
      --rpc --rpcapi eth,web3,shh,admin,debug,miner,personal,txpool,clique
      --networkid 4215 --bootnodes
      enode://$$(cat /root/bootnode)@$$(nslookup eth_bootnode 2>/dev/null | grep 1: | cut -d ' ' -f 3):30301"

  tester:
    # On x86: "ethereum/client-go:stable"
    image: "192.168.15.1:5000/armbuilds/tester"
    depends_on:
      - customer
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == 402raspberrypi_1
    networks:
      - ethnet

  miner:
    image: "192.168.15.1:5000/armbuilds/client"
    deploy:
      placement:
        constraints:
          - node.hostname == 402raspberrypi_6
      replicas: 1
    configs:
      - source: genesis_block
        target: /root/genesis.json
      - source: bootnode_url
        target: /root/bootnode
      - source: miner_key
        target: /root/miner_key
    entrypoint:
      - sh
      - -c
    command: >-
      "geth --datadir /root/data init /root/genesis.json
      && cp /root/miner_key /root/data/keystore/UTC--2018-04-25T17-56-13.344495045Z--43812ca87d1d5196ad1b33382d9c7597a30f21da
      && echo '1fefe00ec80d99ea8f36cec77617c63bf4ebf6af' > /root/password
      && sleep 10
      && geth --datadir /root/data
      --unlock '0x43812ca87d1d5196ad1b33382d9c7597a30f21da'
      --password /root/password
      --mine --etherbase '0x43812ca87d1d5196ad1b33382d9c7597a30f21da'
      --rpc --rpcapi eth,web3,shh,admin,debug,miner,personal,txpool,clique
      --networkid 4215 --bootnodes
      enode://$$(cat /root/bootnode)@$$(nslookup eth_bootnode 2>/dev/null | grep 1: | cut -d ' ' -f 3):30301"
    networks:
      - ethnet

networks:
  ethnet:

configs:
  genesis_block:
    file: ../../blockchain/voltchain.json
  bootnode_url:
    external: true
  bootnode_key:
    external: true
  miner_key:
    file: ../../blockchain/blockdata/keystore/UTC--2018-04-25T17-56-13.344495045Z--43812ca87d1d5196ad1b33382d9c7597a30f21da   
